frequency: 50
sensor_timeout: 0.2
two_d_mode: false
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom
odom0: wheel/odom
odom0_config: [true, true, false, false, false, true, false, false, false, false, false, false, false, false, false]
imu0: imu/data_raw
imu0_config: [false, false, false, true, true, true, true, true, true, false, false, false, false, false, false]
imu0_remove_gravitational_acceleration: true
