local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  obstacle_layer:
    enabled: true
    observation_sources: depth_scan
    depth_scan:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
